seed: 0
exp_name: test   # Experiment name for wandb logging

# Dataset config
data_dir: "processed_data/dolly/full/gpt2/"
max_prompt_length: 256
max_length: 512
train_batch_size: 2
train_num: -1
train_ratio: 1.0
eval_num: 1000
eval_ratio: 1.0
eval_batch_size: 8
eval_every_n_epochs: -1

# Model loading config
model_type: "gpt2"   # choices: [gpt2, llama, opt]
teacher_path: "checkpoints/teacher-gpt2-1.5B"
teacher_precision: "float16"   # choices: [float16, bfloat16, float32]
student_path: "checkpoints/gpt2-base"
student_precision: "bfloat16"  # choices: [float16, bfloat16, float32]

# Training hyperparameters
epochs: 10
optimizer:
  type: AdamW
  lr: 1.0e-5
  weight_decay: 0.05
scheduler:
  type: CosineLRScheduler
  t_initial: ${epochs}
  t_mul: 1
  lr_min: 1.0e-06
  decay_rate: 0.1
  warmup_lr_init: 0.
  warmup_t: 0
  cycle_limit: 1
  t_in_epochs: true
loss:
  alpha: 1.0
  
# Generation hyperparameters
top_k: 0
top_p: 1.0
do_sample: false
no_repeat_ngram_size: 6
repetition_penalty: null
num_beams: 1
temperature: 1.0
